version: "3.8"

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssword
      POSTGRES_USER: el_db_user
      POSTGRES_DB: el_db
    ports:
      - "5432:5432"
volumes:
  my-datavolume:
  postgres_data:
    driver: local