version: "3.8"

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssword
      POSTGRES_USER: el_db_user
      POSTGRES_DB: el_db
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
      image: grafana/grafana
      restart: always
      ports:
          - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=grafana
        - GF_SECURITY_ADMIN_USER=admin
      volumes:
        - ./grafana:/etc/grafana/provisioning/datasources
  collector:
      image: otel/opentelemetry-collector-contrib:0.95.0
      volumes:
        - ./collector-config.yaml:/collector-config.yaml
      command: [ "--config=/collector-config.yaml" ]
      restart: always
      ports:
        - "4317:4317" # OTLP receiver
        - "4318:4318" # OTLP receiver
        - "8889:8889" # Prometheus exporter metrics
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - "3200:3200"
      - "4317"
    volumes:
      - ./tempo.yml:/etc/tempo.yml
volumes:
  my-datavolume:
  postgres_data:
    driver: local