management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/el_db
    username: el_db_user
    password: P@ssword
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql

otel:
  springboot:
    resource:
      attributes:
        service.name: "campaign-service"

#otel:
#  exporter:
#    otlp:
#      endpoint: "http://localhost:4317"
#      traces:
#        protocol: grpc
#      metrics:
#        protocol: grpc
#      logs:
#        protocol: grpc
#
#  traces:
#    sampler:
#      probability: 1.0
